PROJECTION_ROOT_PATH = "/main/ifsapplications/projection/v1"
PLANNING_IFS_CONCURRENCY = 8

STOCK_SELECT_FIELDS = (
    "Contract",
    "PartNo",
    "LocationNo",
    "AvailableQty",
    "QtyOnhand",
    "UoM",
    "LotBatchNo",
    "ObjId",
    "ConfigurationId",
    "SerialNo",
    "EngChgLevel",
    "WaivDevRejNo",
    "ActivitySeq",
    "HandlingUnitId",
)
STOCK_FIELD_MAP = {
    "Contract": "contract",
    "PartNo": "part_no",
    "LocationNo": "location_no",
    "LotBatchNo": "lot_batch_no",
    "AvailableQty": "available_qty",
    "QtyOnhand": "qty_onhand",
    "UoM": "uom",
    "ObjId": "obj_id",
    "ConfigurationId": "configuration_id",
    "SerialNo": "serial_no",
    "EngChgLevel": "eng_chg_level",
    "WaivDevRejNo": "waiv_dev_rej_no",
    "ActivitySeq": "activity_seq",
    "HandlingUnitId": "handling_unit_id",
}

OPERATION_SELECT_FIELDS = (
    "OrderNo",
    "ReleaseNo",
    "SequenceNo",
    "OperationNo",
    "Contract",
    "WorkCenterNo",
    "PartNo",
    "PartNoDesc",
    "PreferredResourceId",
    "OperationNoDesc",
    "RemainingQty",
)
OPERATION_FIELD_MAP = {
    "OrderNo": "order_no",
    "ReleaseNo": "release_no",
    "SequenceNo": "sequence_no",
    "OperationNo": "operation_no",
    "Contract": "contract",
    "WorkCenterNo": "work_center_no",
    "PartNo": "part_no",
    "PartNoDesc": "part_description",
    "PreferredResourceId": "preferred_resource_id",
    "OperationNoDesc": "operation_description",
    "RemainingQty": "remaining_qty",
}

MATERIAL_SELECT_FIELDS = (
    "OrderNo",
    "ReleaseNo",
    "SequenceNo",
    "LineItemNo",
    "OperationNo",
    "PartNo",
    "IssueToLoc",
    "QtyRequired",
    "QtyAssigned",
    "QtyIssued",
    "QtyRemainingToReserve",
    "QtyAvailable",
    "PrintUnit",
    "SoPartNo",
    "Cf_Tercihedilenkaynak",
)
MATERIAL_FIELD_MAP = {
    "OrderNo": "order_no",
    "ReleaseNo": "release_no",
    "SequenceNo": "sequence_no",
    "LineItemNo": "line_item_no",
    "OperationNo": "operation_no",
    "PartNo": "part_no",
    "IssueToLoc": "issue_to_location",
    "QtyRequired": "qty_required",
    "QtyAssigned": "qty_assigned",
    "QtyIssued": "qty_issued",
    "QtyRemainingToReserve": "qty_remaining_to_reserve",
    "QtyAvailable": "qty_available",
    "PrintUnit": "print_unit",
    "SoPartNo": "produced_part_no",
    "Cf_Tercihedilenkaynak": "machine",
}
